[project]
name = "causal_cut_tool"
description = "Implementation of causal cut tool for cyber-digital system testing"
requires-python = ">=3.10"
dynamic = ["version", "dependencies"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["tmp*"]
