[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools<=81", "setuptools_scm[toml]>=6.2", "wheel"]

[project]
name = "causal_cut_plugin"
description = "Plugin for causal cut testing tool"
requires-python = ">=3.10"
dynamic = ["version"]

[tool.setuptools.packages.find]
exclude = ["tmp*"]

[project.entry-points."causal_cut_tool.run"]
run = "causal_cut_plugin:run"

[project.entry-points."causal_cut_tool.find_faults"]
find_faults = "causal_cut_plugin:find_faults"